_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

log_every_n_steps: 64

gradient_clip_val: 0.5
gradient_clip_algorithm: 'value'
accumulate_grad_batches: 7

limit_train_batches: 3500
limit_val_batches: 250
limit_test_batches: 3500
val_check_interval: 0.1