_target_: src.models.glow_module.GlowLitModule

net:
  _target_: src.models.components.glow.Glow
  n_flows: 3
  depth: 32
  in_channels: 3
  hid_channels: 128
  image_size: ${...image_size}

evaluator:
  _target_: src.evaluator.evaluator.Evaluator
  evaluators:
    - ${....FIDEvaluator}

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-3
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: True
  max_lr: 1e-2
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 25000

