Resize:
  _target_: albumentations.Resize
  height: ${...image_size}
  width: ${...image_size}

Normalize:
  _target_: albumentations.Normalize
  mean: 0.5
  std: 0.5

ToTensorV2:
  _target_: albumentations.pytorch.ToTensorV2
