# @package _global_

# uses only 1% of the training data and 5% of validation/test data

task_name: "debug"

trainer:
  max_epochs: 1
  limit_train_batches: 50
  limit_val_batches: 50
  limit_test_batches: 50
  log_every_n_steps: 1
  check_val_every_n_epoch: 1
